{% set version = "0.1-6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-trimcluster
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/trimcluster_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/trimcluster/trimcluster_{{ version }}.tar.gz
  sha256: 4293e70a4b1c0f53f879be713d8a7a6ca629b4e34bf79ce26451e02bf1a9a9ae

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('trimcluster')"           # [not win]
    - "\"%R%\" -e \"library('trimcluster')\""  # [win]

about:
  home: http://www.homepages.ucl.ac.uk/~ucakche/
  license: GPL-3
  summary: Trimmed k-means clustering. The method is described in Cuesta-Albertos et al. (1997) <doi:10.1214/aos/1031833664>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: trimcluster
# Title: Cluster Analysis with Trimming
# Version: 0.1-5
# Date: 2020-02-08
# VersionNote: Released 0.1-2.1 on 2018-07-20 on CRAN
# Author: Christian Hennig <chrish@stats.ucl.ac.uk>
# Depends: R (>= 1.9.0)
# Suggests: fpc
# Description: Trimmed k-means clustering. The method is described in Cuesta-Albertos et al. (1997) <doi:10.1214/aos/1031833664>.
# Maintainer: Valentin Todorov <valentin.todorov@chello.at>
# License: GPL
# URL: http://www.homepages.ucl.ac.uk/~ucakche/
# Packaged: 2020-02-08 18:29:38 UTC; Share
# Repository: CRAN
# Date/Publication: 2020-02-09 12:10:02 UTC
# NeedsCompilation: no
