{% set version = '0.1-2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-trimcluster
  version: {{ version|replace("-", "_") }}

source:
  fn: trimcluster_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/trimcluster_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/trimcluster/trimcluster_{{ version }}.tar.gz
  sha256: b64a872a6c2ad677dfeecc776c9fe5aff3e8bab6bc6a8c86957b5683fd5d2300

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('trimcluster')"           # [not win]
    - "\"%R%\" -e \"library('trimcluster')\""  # [win]

about:
  home: http://www.homepages.ucl.ac.uk/~ucakche/
  license: GPL
  summary: Trimmed k-means clustering.
  license_family: GPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
