{% set version = "0.1-5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-trimcluster
  version: {{ version|replace("-", "_") }}

source:
  fn: trimcluster_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/trimcluster_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/trimcluster/trimcluster_{{ version }}.tar.gz
  sha256: 9239f20e4a06ac2fa89e5d5d89b23a45c8c534a7264d89bede8a35d43dda518b

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('trimcluster')"           # [not win]
    - "\"%R%\" -e \"library('trimcluster')\""  # [win]

about:
  home: http://www.homepages.ucl.ac.uk/~ucakche/
  license: GPL
  summary: Trimmed k-means clustering.
  license_family: GPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
