travis:
  secure:
    BINSTAR_TOKEN: TY4bByKhEaItOiz35b74lzWqXjq3mM3TZMxHexgzudIRmg7PNC+tQvxaw3UKiK7A1zYmoTzzaWS9wZcdliKLQKthGGnt/uY3wh+2eBm8xKUd6x16H0kbRF4JVlVXFKdsQSbwKbpZUJS7xwdDQ8QpvCy0yBBW+C31l6EEGrBazriQhYZq9WzCggZLn+1bYByVdFBRyCswy8A3CaKkMA5d7+V95JIUXGueP8BKeBrVuKij7oqdpGMENzkUmfqjr3PKiTHdLqcQ3GtdvUqt/SGHG8HTRTOKvdOGeHTZjjWRk7lOnNGV4GmoSOH7KEY+kzzHrs0pVc4wHsWnLez7k9XUA61UXH7YJKMq5RJY3yC+uE06zB39M5Rc5AkdF1WpLJtX/x+Mf2trcgAFNInXL/F1N1T0jng/YSGbluXHBC3D2VtEj00O/lJnIX7khPILAXAtdag5xxFufx94dLfQBa2SkE6tk0th3D5dHsXj7grVHsM+KYdlwlJqip+h4K+N2+9PYUo1iwN4z90UpMHwcGG7yQLC8KaJFFBdqOCNtEdnLLOiS/emE6sYd07OIZQX5h/yS4BnxhksvGQ4MyBFGtw/GaJXpOzSL/j2CqfGvxk2JBW7DBaVrRjAf9jt3Hr8DWuuzBR652iEiGiHTl03VEF37tlzAZ8QZvRkKWSAHdDJkes=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
