appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: LZNmhnO+TAMlBLrtrv6pRO2JOKyBg5C2igQyXVm8dy4niurKZPDoIytaO27QEDlVJ3vJxmPsF8iNywgm+tktzw9mPp/5WmT2BCwkX78iBEaSi/p7jVmJy04xXwmUNKDPgs5oIIAybTEOzY5gtLmsn0BL033As8mxY6830LDcfT3+jLGFWKS232+JE/OqB1CnNVrQlQngwc5gHUIsBnd12+VZvuq6MgICArevvoVA/qjuQ607om0lP5lPpndzzlPOmClicor3WT2zwD6ZnQSPiPzedLEFkr1jJpqnbpzdko7nBt2arBUFVO5rWjK31I4FNSOK5kRseRMb8/Az/5Y0viXS9wTOQkp6rIn2qB7matWm/KAZrTpw9ClgwpKvKT+ZkWQnCq2kIn/lwFQEx+CPI8PZJ9xKjO8uZzbIF4HEQFjNlAaPlkX+pC3IA8JtQIVvMuU/ydwNTzKQ5u3tZaoxLkYv8EHFWWkNSzNiUStJg1f6SHzu4D0HvpVZ0RJLWn+sp/Av3HeFoBfkswTN8pLBTLG2Fn4pUaS0nTEpyoOS9gjqPH7mztl2NuXeAi0gfKGUnpokWVBa4ZDtUMcmLZIco/3r6cMpYEfrk9+WIlNd6esvFxlRKanp2dBaAM1IS+U3cxY8wt/QurAuV/ua7QdsVUZjAnpgnEVhPL2n1Z+IjCs=}
bot:
  automerge: true
